export const GET_USER_ID = 'GET_USER_ID';
export const CREATE_USER_REQUEST = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
