export const ADD_TICKET_TO_CART = 'ADD_TICKET_TO_CART';
export const REMOVE_TICKET_FROM_CART = 'REMOVE_TICKET_FROM_CART';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAILURE = 'CREATE_CART_FAILURE';

export const GET_TOTAL = 'GET_TOTAL';
