export const FETCH_VENUES_REQUEST = 'FETCH_VENUES_REQUEST';
export const FETCH_VENUES_SUCCESS = 'FETCH_VENUES_SUCCESS';
export const FETCH_VENUES_FAILURE = 'FETCH_VENUES_FAILURE';

export const FETCH_VENUE_REQUEST = 'FETCH_VENUE_REQUEST';
export const FETCH_VENUE_SUCCESS = 'FETCH_VENUE_SUCCESS';
export const FETCH_VENUE_FAILURE = 'FETCH_VENUE_FAILURE';
